### ISSUE TITLE
Watchman 4.9.0 fails to build on RHEL 6.6

### ISSUE THREAD

**Issue by stephenh** [facebook/watchman#534]
RHEL 6.6 has kernel 2.6.32, so no O_PATH. (I was able to get g++ 4.8 installed via a CERN repo, but seems unlikely I'll be able to do a kernel upgrade.)

`make` fails with this error:

```
  CXXLD  tests/childproc.t
tests_childproc_t-FileDescriptor.o: In function `checkCanonicalBaseName':
/home/shaberma/other/watchman/FileDescriptor.cpp:187: undefined reference to `w_dir_open(char const*, bool)'
```

Understood this is an old platform, but it's a corporate box/cannot upgrade/etc./etc.

**Comment by wez** [comment]
Sorry for the long delay in responding, but if you run `make watchman` does that succeed?  I think you're just hitting a problem compiling a test case

**Comment by stephenh** [comment]
Hey; thanks for the follow up. I don't have access to a RHEL 6.6 machine anymore, so will just close this.

**Comment by kwlzn** [comment]
can confirm that `make watchman` gets past this on centos6 (using the scl devtoolset-7).

**Comment by wez** [comment]
```
diff --git a/Makefile.am b/fbcode/watchman/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -265,6 +265,7 @@
        PubSub.cpp \
        string.cpp \
        hash.cpp \
+       opendir.cpp \
        log.cpp
 
 tests_cache_t_CPPFLAGS = $(THIRDPARTY_CPPFLAGS) @IRONMANCFLAGS@
```

I suspect that we need this to resolve this issue; can you try this out and confirm and I can get this landed?

**Comment by kwlzn** [comment]
@wez applying that diff resolves the `make` breakage on centos6 for me.

**Comment by kaleidoc0de** [comment]
I have a failing build on centos-release-6-10
gcc version 7.3.1 20180303 

`tests_childproc_t-FileDescriptor.o: In function `watchman::checkCanonicalBaseName(char const*)':
/root/watchman/FileDescriptor.cpp:187: undefined reference to `w_dir_open(char const*, bool)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1068: tests/childproc.t] Error 1
make[1]: Leaving directory '/root/watchman'
make: *** [Makefile:814: all] Error 2`

I tried checkout 4.7.0 for watchman and it fails earlier at

`hash.c: In function ‘w_hash_bytes’:
hash.c:228:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 12: c+=((uint32_t)k[11])<<24;
                ~^~~~~~~~~~~~~~~~~~~~~~~
hash.c:229:7: note: here
       case 11: c+=((uint32_t)k[10])<<16;
       ^~~~
hash.c:229:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 11: c+=((uint32_t)k[10])<<16;
                ~^~~~~~~~~~~~~~~~~~~~~~~
hash.c:230:7: note: here
       case 10: c+=((uint32_t)k[9])<<8;
       ^~~~
hash.c:230:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 10: c+=((uint32_t)k[9])<<8;
                ~^~~~~~~~~~~~~~~~~~~~~
hash.c:231:7: note: here
       case 9 : c+=k[8];
       ^~~~
hash.c:231:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 9 : c+=k[8];
                ~^~~~~~
hash.c:232:7: note: here
       case 8 : b+=((uint32_t)k[7])<<24;
       ^~~~
hash.c:232:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 8 : b+=((uint32_t)k[7])<<24;
                ~^~~~~~~~~~~~~~~~~~~~~~
hash.c:233:7: note: here
       case 7 : b+=((uint32_t)k[6])<<16;
       ^~~~
hash.c:233:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 7 : b+=((uint32_t)k[6])<<16;
                ~^~~~~~~~~~~~~~~~~~~~~~
hash.c:234:7: note: here
       case 6 : b+=((uint32_t)k[5])<<8;
       ^~~~
hash.c:234:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 6 : b+=((uint32_t)k[5])<<8;
                ~^~~~~~~~~~~~~~~~~~~~~
hash.c:235:7: note: here
       case 5 : b+=k[4];
       ^~~~
hash.c:235:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 5 : b+=k[4];
                ~^~~~~~
hash.c:236:7: note: here
       case 4 : a+=((uint32_t)k[3])<<24;
       ^~~~
hash.c:236:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 4 : a+=((uint32_t)k[3])<<24;
                ~^~~~~~~~~~~~~~~~~~~~~~
hash.c:237:7: note: here
       case 3 : a+=((uint32_t)k[2])<<16;
       ^~~~
hash.c:237:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 3 : a+=((uint32_t)k[2])<<16;
                ~^~~~~~~~~~~~~~~~~~~~~~
hash.c:238:7: note: here
       case 2 : a+=((uint32_t)k[1])<<8;
       ^~~~
hash.c:238:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       case 2 : a+=((uint32_t)k[1])<<8;
                ~^~~~~~~~~~~~~~~~~~~~~
hash.c:239:7: note: here
       case 1 : a+=k[0];
       ^~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2219: watchman-hash.o] Error 1
make[1]: Leaving directory '/root/watchman'
make: *** [Makefile:591: all] Error 2
`
