### ISSUE TITLE
No linux build on releases since 04-2024

### ISSUE THREAD

**Issue by dougg0k** [facebook/watchman#1272]
Hi,

There are no linux build being included in the releases assets since https://github.com/facebook/watchman/releases/tag/v2024.04.15.00

https://github.com/facebook/watchman/releases/latest All the latest has been for windows only or none.

---

Checking the logs, seems that linux build are set to continue on error. So were just left like that.

https://github.com/facebook/watchman/actions/runs/13117637176/job/36595750886

Most errors seem tied to `/folly/Portability.h:41:24: error: static assertion failed: __GNUC__ >= 10`

https://clang.llvm.org/docs/UsersManual.html#cmdoption-fgnuc-version Outdated clang?

---

Can you fix?

Thanks.

**Comment by sovetski** [comment]
same here

**Comment by dougg0k** [comment]
Same there what?

**Comment by awilkins** [comment]
Thanks for linking the last build, anyway .... currently building it from source and wowzer, it takes some time, about 5x as long as a Linux kernel build.

OK, it just finished.

**Comment by dougg0k** [comment]
Someone seems to have fixed it, but they didnt mentioned it here.

https://github.com/facebook/watchman/releases/tag/v2025.04.14.00

**Comment by 911t** [comment]
There is once again no Linux build on the latest [v2025.04.21.00](https://github.com/facebook/watchman/releases/tag/v2025.04.21.00) release though.

**Comment by dougg0k** [comment]
That might be for another issue though, as it has been releases after the date mentioned.

**Comment by awilkins** [comment]
Suspect this is because of #1276 

Hypothesis here would be that because installing all the libs that the Watchman build draws in breaks debtools, it cannot complete a Debian package as part of the build.

**Comment by Dialga** [comment]
reopen for 2025.11.03
