### ISSUE TITLE
"abort: The process cannot access the file because it is being used by another process" with latest Windows watchman build

### ISSUE THREAD

**Issue by rvandermeulen** [facebook/watchman#197]
I've been testing watchman with Mozilla's MozillaBuild package. Today, I updated my test build to rev 2ca4c24 from rev d1d427f and am now getting the following error whenever I try to use mq for anything (haven't tried other commands to see what else is affected):

$ hg qref -e
abort: The process cannot access the file because it is being used by another process
Exception AttributeError: "'dirstateguard' object has no attribute '_active'" in <bound method dirstateguard.__del__ of <mercurial.cmdutil.dirstateguard object at 0x02752D10>> ignored

Regression from rev ff658c9 I'm guessing? I'm on Win10 x64 and Mercurial 3.6.3 on top of Python 2.7.11. I can happily provide you with any other debugging info you request.

**Comment by rvandermeulen** [comment]
I can confirm that this regressed with rev ff658c99.

**Comment by wez** [comment]
I don't have a win system handy to try to repro this right now.  Do you know what file that abort message was referencing?
Can you share your watchman log file?

**Comment by rvandermeulen** [comment]
I'm afraid I don't know what file it's aborting on. Where would I find the watchman log file? I see watchman.state in the .hg dir but that's it.

**Comment by wez** [comment]
https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs
applies in general, but doesn't have any windows specific text.  You should find the log file somewhere in your TMP dir.

You may be able to use a tool like FileMon to figure out the path that is causing problems

**Comment by rvandermeulen** [comment]
Bingo!

2016-01-04T15:35:05,602: [listener] Watchman 4.3.0 <no build info set> starting up on StarsEnd
2016-01-04T15:35:05,602: [listener] Using watcher mechanism win32
2016-01-04T15:35:05,602: [listener] failed to parse json from C:/Users/Ryan/AppData/Local/Temp\Ryan-state\state: unable to open C:/Users/Ryan/AppData/Local/Temp\Ryan-state\state: No such file or directory
2016-01-04T15:35:05,602: [listener] waiting for pipe clients on \\.\pipe\watchman-Ryan
2016-01-04T15:35:05,610: [client:stm=0000026C94EF63A0] send_error_response: unable to resolve root c:\Users\Ryan\repos\mozilla-build: directory C:\Users\Ryan\repos\mozilla-build is not watched
2016-01-04T15:35:05,610: [client:stm=0000026C94EF63A0] path C:\Users\Ryan\repos\mozilla-build is on filesystem type NTFS
2016-01-04T15:35:05,655: [io C:\Users\Ryan\repos\mozilla-build] crawl complete
2016-01-04T15:35:05,697: [io C:\Users\Ryan\repos\mozilla-build] w_lstat(C:\Users\Ryan\repos\mozilla-build\.hg\.dirstate-j4o8o1) 13 Permission denied

**Comment by rvandermeulen** [comment]
The "Permission denied" error doesn't seem relevant as I see those in working instances as well.

**Comment by wez** [comment]
Can you try using https://technet.microsoft.com/en-us/sysinternals/bb896645 to figure out which path(s) are the subject of the permission denied errors?

**Comment by wez** [comment]
Any chance that you provide the requested information?

**Comment by rvandermeulen** [comment]
Sorry, I've been busy lately and then got intermittent internet connectivity dumped on top to add to the fun. I'll get it to you as soon as I'm able.

**Comment by rvandermeulen** [comment]
I've been trying to catch this with Process Monitor, but the amount of output from watchman.exe is staggeringly high (tens out thousands of entries in the split second from me entering |hg qref| to stopping further logging).

**Comment by wez** [comment]
Likely resolved by https://github.com/facebook/watchman/commit/30f295efa1ed4d2759f723204d591bf1631511c5
