### ISSUE TITLE
Cannot compile on focal fossa 20.04

### ISSUE THREAD

**Issue by aurore-ry** [facebook/watchman#989]
scm/Mercurial.cpp: In constructor ‘watchman::Mercurial::infoCache::infoCache(std::string)’:
scm/Mercurial.cpp:16:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct watchman::FileInformation’; use assignment or value-initialization instead [-Werror=class-memaccess]
   16 |   memset(&dirstate, 0, sizeof(dirstate));
      |                                        ^
In file included from scm/Mercurial.h:10,
                 from scm/Mercurial.cpp:3:
./FileInformation.h:18:8: note: ‘struct watchman::FileInformation’ declared here
   18 | struct FileInformation {
      |        ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:4446 : scm/watchman-Mercurial.o] Erreur 1
make[1] : on quitte le répertoire « /home/xana/watchman »
make: *** [Makefile:1264 : all] Erreur 2

**Comment by chadaustin** [comment]
Thanks. I'm working on some CI for this, and I'll report back soon! Are you building with ./autogen.sh without any customizations?

**Comment by chadaustin** [comment]
Actually, looks like this was fixed a while ago! You must have old source code.

**Comment by aurore-ry** [comment]
Yes the problem is solved :) Thank you for your answer!
