### ISSUE TITLE
Unable to build on macOS 10.14

### ISSUE THREAD

**Issue by 1st1** [facebook/watchman#651]
Building v4.9.0 via macports or manually results in an error:

```
bser.cpp:345:17: error: offset of on non-standard-layout type 'json_object_t'
      [-Werror,-Winvalid-offsetof]
  auto object = json_to_object(obj);
                ^~~~~~~~~~~~~~~~~~~
./thirdparty/jansson/jansson_private.h:71:32: note: expanded from macro 'json_to_object'
#define json_to_object(json_)  container_of((json_t*)json_, json_object_t, json)
                               ^                                           ~~~~
./thirdparty/jansson/jansson_private.h:19:31: note: expanded from macro 'container_of'
    ((type_ *)((char *)ptr_ - offsetof(type_, member_)))
                              ^               ~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/stddef.h:120:24: note:
      expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
1 error generated.
make[1]: *** [watchman-bser.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

-------------

<details>
<summary>./configure output</summary>

```
~/d/s/watchman ((v4.9.0)) » ./configure
checking build system type... x86_64-apple-darwin18.0.0
checking host system type... x86_64-apple-darwin18.0.0
checking target system type... x86_64-apple-darwin18.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.0.0 file names to x86_64-apple-darwin18.0.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.0.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for ld used by g++ -std=c++11... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ -std=c++11 linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ -std=c++11 option to produce PIC... -fno-common -DPIC
checking if g++ -std=c++11 PIC flag -fno-common -DPIC works... yes
checking if g++ -std=c++11 static flag -static works... no
checking if g++ -std=c++11 supports -c -o file.o... yes
checking if g++ -std=c++11 supports -c -o file.o... (cached) yes
checking whether the g++ -std=c++11 linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking dependency style of gcc... gcc3
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libfolly... no
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for pcre-config... /opt/local/bin/pcre-config
checking for PCRE using /opt/local/bin/pcre-config... 8.42
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for library containing pthread_create... none required
checking for library containing socket... none required
checking for library containing SHA1_Init... -lcrypto
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking sys/inotify.h usability... no
checking sys/inotify.h presence... no
checking for sys/inotify.h... no
checking sys/event.h usability... yes
checking sys/event.h presence... yes
checking for sys/event.h... yes
checking sys/ucred.h usability... yes
checking sys/ucred.h presence... yes
checking for sys/ucred.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for mkostemp... yes
checking for kqueue... yes
checking for port_create... no
checking for inotify_init... no
checking for strtoll... yes
checking for localeconv... yes
checking for statfs... yes
checking for accept4... no
checking for inotify_init1... no
checking for getattrlistbulk... yes
checking for openat... yes
checking for fdopendir... yes
checking for pipe2... no
checking for sys/vfs.h... no
checking for sys/param.h... yes
checking for sys/mount.h... yes
checking for sys/statfs.h... no
checking for sys/statvfs.h... yes
checking valgrind/valgrind.h usability... no
checking valgrind/valgrind.h presence... no
checking for valgrind/valgrind.h... no
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking CoreServices/CoreServices.h usability... yes
checking CoreServices/CoreServices.h presence... yes
checking for CoreServices/CoreServices.h... yes
checking for FSEventStreamSetExclusionPaths... yes
checking for backtrace... yes
checking for backtrace_symbols... yes
checking for backtrace_symbols_fd... yes
checking for sys_siglist... yes
checking for memmem... yes
checking for struct statvfs.f_fstypename... no
checking for struct statvfs.f_basetype... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating thirdparty/jansson/jansson_config.h
config.status: creating cppclient/watchmanclient.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Your build configuration:

        CC = gcc
        CPPFLAGS =  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/opt/local/include
        CFLAGS = -g -O2 -I/opt/local/include -Wall -Wextra -Wdeclaration-after-statement -g -gdwarf-2 -fno-omit-frame-pointer
        CXX = g++ -std=c++11
        CXXFLAGS = -g -O2 -Wall -Wextra -g -gdwarf-2 -fno-omit-frame-pointer
        LDFLAGS =
        prefix: /usr/local
        version: 4.9.0
        state directory: /usr/local/var/run/watchman
```

</details>

**Comment by 1st1** [comment]
Looks like it's been fixed in the master branch.

**Comment by djtriptych** [comment]
I had the same problem, and master didn't work for me.

This did work:

```
./autogen.sh
./configure
git checkout master bser.cpp
git checkout master thirdparty/jansson/
make
# Had to run this manually for some reason.
cd python && /usr/bin/python ./setup.py clean build_py -c -d . build_ext -i
sudo make install
```

**Comment by fozcode** [comment]
Running make from master kicked off homebrew for me, which I didn't want as it tries to install 19 dependencies and they conflict with things I already have installed.

In the steps by @djtriptych I only needed to check out `thirdparty/jansson/` on top of v4.9.0, but to commit `061e6ab` as the latest code in master has changed significantly.
