### ISSUE TITLE
Does not compile on Ubuntu with GCC 4.7.3

### ISSUE THREAD

**Issue by timjstewart** [facebook/watchman#2]
% make
make  all-am
make[1]: Entering directory `/home/tim/tmp/watchman'
gcc -DHAVE_CONFIG_H -I.  -Ithirdparty/jansson -Werror -D_REENTRANT  -g -O2  -Wall -Wextra -Wdeclaration-after-statement -g -gdwarf-2 -fno-omit-frame-pointer -MT watchman-opt.o -MD -MP -MF .deps/watchman-opt.Tpo -c -o watchman-opt.o`test -f 'opt.c' || echo './'`opt.c
opt.c: In function ‘w_getopt’:
opt.c:201:19: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
cc1: all warnings being treated as errors
make[1]: *** [watchman-opt.o] Error 1
make[1]: Leaving directory`/home/tim/tmp/watchman'
make: **\* [all] Error 2

If I hack the code to not ignore asprintf, it gets further:

ht.c: In function ‘w_ht_string_copy’:
ht.c:370:19: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ht.c: In function ‘w_ht_string_del’:
ht.c:376:19: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ht.c: In function ‘w_ht_string_equal’:
ht.c:381:25: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ht.c:381:41: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
ht.c: In function ‘w_ht_string_hash’:
ht.c:386:11: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
cc1: all warnings being treated as errors
make[1]: **\* [watchman-ht.o] Error 1
make[1]: Leaving directory `/home/tim/src/watchman'
make: **\* [all] Error 2

It compiled great on my Mac (GCC 4.2.1).
